[project]
name = "frameworkless"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pymysql>=1.1.1",
    "sqlalchemy>=2.0.36",
    "uvicorn>=0.34.0",
]
